[package]
name = "rust_aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
itertools = "0.10.5"
regex = "1"
typed-arena = "2.0.1"
queues = "1.0.2"
sscanf = "0.4.0"
